version: "3.8"

services:
  php:
    container_name: ep7.app
    image: "webdevops/php-apache:8.3"
    ports:
      - 8085:80
    volumes:
      - ./src:/app

  db:
    container_name: ep7.db
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3310:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db: {}

networks:
  default:
    name: mynet